version: '3.8'
services:
  kaptifi-vision-marshal:
    build: .
    container_name: kaptifi-vision-marshal
    restart: always
    command: uvicorn api.main:app --host ${HOST} --port ${PORT}
    ports:
      - "8500:${PORT}"
    volumes:
      - ./logs_data:/app/logs
      - ./config_data:/app/config
    env_file:
      - .env

volumes:
  logs_data:
  config_data:
